CC = gcc -std=c11
FLAGS = -Wall -Wextra -Werror
RM = rm -f

default: all
all: Q1 Q2 Q3 Q4

Q1: Q1.c
	$(CC) $(FLAGS) -o q1 Q1.c

Q2: Q2.c
	$(CC) $(FLAGS) -o q2 Q2.c

Q3: Q3.c
	$(CC) $(FLAGS) -o q3 Q3.c

Q4: Q4.c
	$(CC) $(FLAGS) -o q4 Q4.c

clean:
	$(RM) q1 q2 q3 q4
